# Generated by Django 3.0.3 on 2020-03-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=100)),
                ('imageUrl', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=10)),
                ('availability', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('place', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=100)),
                ('startTime', models.CharField(max_length=10)),
                ('endTime', models.CharField(max_length=10)),
                ('weekDay', models.PositiveSmallIntegerField()),
                ('appointment_id', models.CharField(max_length=200)),
                ('service_id', models.CharField(max_length=200)),
                ('pay', models.BooleanField()),
                ('appointment', models.BooleanField()),
                ('teacher_v2', models.ManyToManyField(related_name='related_teacher', to='fitapi.Teacher')),
            ],
        ),
    ]
